test of tier0 in/out tree tests

diff --git a/jenkins-job-builder/freeipa-jobs.yaml b/jenkins-job-builder/freeipa-jobs.yaml
--- a/jenkins-job-builder/freeipa-jobs.yaml
+++ b/jenkins-job-builder/freeipa-jobs.yaml
@@ -234,36 +234,99 @@
             report-mail-address: '{report-mail-address}'
     publishers:
         - trigger:
-            project: '{prefix}-intree-tests-{project}'
+            project: '{prefix}-intree-tests-{project}-tier0'
         - trigger:
-            project: '{prefix}-outoftree-tests-{project}'
-        - trigger:
-            project: '{prefix}-webui-firefox-{project}-with-dns-with-ca'
-        - trigger:
-            project: '{prefix}-webui-firefox-{project}-no-dns-no-ca'
-        - trigger:
-            project: '{prefix}-integration-{project}-simple_replication'
-        - trigger:
-            project: '{prefix}-integration-{project}-caless'
-        - trigger:
-            project: '{prefix}-integration-{project}-basic_trust'
-        - trigger:
-            project: '{prefix}-integration-{project}-external_ca'
-        - trigger:
-            project: '{prefix}-integration-{project}-forced_client_reenrollment'
-        - trigger:
-            project: '{prefix}-integration-{project}-kerberos_flags'
-        - trigger:
-            project: '{prefix}-integration-{project}-sudo'
-        - trigger:
-            project: '{prefix}-integration-{project}-legacy_clients'
-        - trigger:
-            project: '{prefix}-integration-{project}-service_permissions'
-        - trigger:
-            project: '{prefix}-integration-{project}-backup_and_restore'
+            project: '{prefix}-outoftree-tests-{project}-tier0'
+
+#- job-template:
+#    name: '{prefix}-intree-tests-{project}'
+#    node: freeipa-runner-{os}
+#    defaults: global
+#    description: |
+#        Run the FreeIPA test suite (sans WebUI & Integration), in-tree.
+#    scm:
+#        - freeipa-fedorahosted:
+#            git-branch: "{git-branch}"
+#            git-url: "{git-url}"
+#            git-browser-url: "{git-browser-url}"
+#    wrappers:
+#        - workspace-cleanup
+#    builders:
+#        - clean-up-environment
+#        - install-built-rpms:
+#            prefix: "{prefix}"
+#            project: "{project}"
+#            os: "{os}"
+#            git-branch: "{git-branch}"
+#        - shell: |
+#            # We're running in-tree tests, but we get compiled files from RPMs
+#            cp /usr/lib/python2.7/site-packages/ipapython/version.py ipapython/version.py
+#            cp /usr/lib/python2.7/site-packages/ipaplatform/services.py ipaplatform/services.py
+#            cp /usr/lib/python2.7/site-packages/ipaplatform/paths.py ipaplatform/paths.py
+#            cp /usr/lib/python2.7/site-packages/ipaplatform/tasks.py ipaplatform/tasks.py
+#        - install:
+#            options-dns-setup: "{options-dns-setup}"
+#            options-ca-setup: "{options-ca-setup}"
+#        - setup-default-conf
+#        - shell: |
+#            # set up cert
+#            rm -rvf ~/.ipa/alias
+#            sudo cp -R /etc/httpd/alias ~/.ipa/alias
+#            sudo cp  /etc/httpd/alias/pwdfile.txt ~/.ipa/alias/.pwd
+#            sudo chown -R jenkins:jenkins ~/.ipa/alias/
+#            rm tests/test_xmlrpc/service.crt || :
+#        - shell: |
+#            # Jenkins sets the PATH to its own default,
+#            # compensate so ipa-getkeytab can be found
+#            export PATH=$PATH:/usr/sbin
+#
+#            ./make-test -v --with-xunit || :
+#        - uninstall
+#    publishers:
+#        - nosetests-xunit
+#        - mail-on-fail:
+#            report-mail-address: '{report-mail-address}'
+#    triggers:
+#        - timed:
+#            # Do the check nightly
+#            "H H(0-5) * * *"
+#
+#- job-template:
+#    name: '{prefix}-outoftree-tests-{project}'
+#    node: freeipa-runner-{os}
+#    defaults: global
+#    description: |
+#        Run the FreeIPA test suite (sans WebUI & Integration), out-of-tree.
+#    wrappers:
+#        - workspace-cleanup
+#    builders:
+#        - clean-up-environment
+#        - install-built-rpms:
+#            prefix: "{prefix}"
+#            project: "{project}"
+#            os: "{os}"
+#            git-branch: "{git-branch}"
+#        - install:
+#            options-dns-setup: "{options-dns-setup}"
+#            options-ca-setup: "{options-ca-setup}"
+#        - setup-default-conf
+#        - shell: |
+#            # Jenkins sets the PATH to its own default,
+#            # compensate so ipa-getkeytab can be found
+#            export PATH=$PATH:/usr/sbin
+#
+#            ipa-run-tests -v --with-xunit || :
+#        - uninstall
+#    publishers:
+#        - nosetests-xunit
+#        - mail-on-fail:
+#            report-mail-address: '{report-mail-address}'
+#        - trigger:
+#            threshold: SUCCESS
+#            project: '{prefix}-integration-{project}-basic_trust'
 
 - job-template:
-    name: '{prefix}-intree-tests-{project}'
+    name: '{prefix}-intree-tests-{project}-tier0'
     node: freeipa-runner-{os}
     defaults: global
     description: |
@@ -303,8 +366,8 @@
             # Jenkins sets the PATH to its own default,
             # compensate so ipa-getkeytab can be found
             export PATH=$PATH:/usr/sbin
-
-            ./make-test -v --with-xunit || :
+    
+            ./make-test -v --with-xunit -m tier0 || :
         - uninstall
     publishers:
         - nosetests-xunit
@@ -316,7 +379,7 @@
             "H H(0-5) * * *"
 
 - job-template:
-    name: '{prefix}-outoftree-tests-{project}'
+    name: '{prefix}-outoftree-tests-{project}-tier0'
     node: freeipa-runner-{os}
     defaults: global
     description: |
@@ -339,7 +402,7 @@
             # compensate so ipa-getkeytab can be found
             export PATH=$PATH:/usr/sbin
 
-            ipa-run-tests -v --with-xunit || :
+            ipa-run-tests -v --with-xunit -m tier0 || :
         - uninstall
     publishers:
         - nosetests-xunit
@@ -429,146 +492,30 @@
         - '{prefix}-stats-{project}'
         - '{prefix}-build-{project}'
         - '{prefix}-check-deps-{project}'
-        - '{prefix}-intree-tests-{project}'
-        - '{prefix}-outoftree-tests-{project}'
-        - '{prefix}-webui-{browser}-{project}-{prettyname}':
+        - '{prefix}-intree-tests-{project}-tier0'
+        - '{prefix}-outoftree-tests-{project}-tier0':
             prettyname: with-dns-with-ca
             noca: False
             nodns: False
             browser: firefox
-        - '{prefix}-webui-{browser}-{project}-{prettyname}':
-            prettyname: no-dns-no-ca
-            noca: True
-            nodns: True
-            browser: firefox
-            options-dns-setup: ""
-            options-ca-setup: >
-                --http_pkcs12 star-cert.p12 \
-                --dirsrv_pkcs12 star-cert.p12 \
-                --http_pin $FREEIPACI_STAR_CERT_PIN --dirsrv_pin $FREEIPACI_STAR_CERT_PIN \
-                --root-ca-file star-cert-ca.crt
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: caless
-            suite: test_integration/test_caless.py
-            controller_suffix: ''
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: master
-                      - name: replica.ipa.test
-                        role: replica
-                      - name: client.ipa.test
-                        role: client
-                    name: ipa.test
-                    type: IPA
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: simple_replication
-            suite: test_integration/test_simple_replication.py
-            controller_suffix: ''
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: master
-                      - name: replica.ipa.test
-                        role: replica
-                    name: ipa.test
-                    type: IPA
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: external_ca
-            suite: test_integration/test_external_ca.py
-            controller_suffix: ''
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: master
-                    name: ipa.test
-                    type: IPA
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: forced_client_reenrollment
-            suite: test_integration/test_forced_client_reenrollment.py
-            controller_suffix: ''
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: master
-                      - name: replica.ipa.test
-                        role: replica
-                      - name: client.ipa.test
-                        role: client
-                    name: ipa.test
-                    type: IPA
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: kerberos_flags
-            suite: test_integration/test_kerberos_flags.py
-            controller_suffix: ''
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: master
-                      - name: client.ipa.test
-                        role: client
-                    name: ipa.test
-                    type: IPA
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: sudo
-            suite: test_integration/test_sudo.py
-            controller_suffix: ''
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: master
-                      - name: client.ipa.test
-                        role: client
-                    name: ipa.test
-                    type: IPA
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: basic_trust
-            suite: test_integration/test_trust.py
-            controller_suffix: '-trusts'
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: trust_master
-                    name: ipa.test
-                    type: TRUST_IPA
-                  - hosts:
-                      - name: ad.ad.test
-                        role: ad
-                      - name: child.child.ad.test
-                        role: ad_subdomain
-                    name: ad.test
-                    type: AD
-        - '{prefix}-integration-{project}-{pretty_name}':
-            pretty_name: legacy_clients
-            suite: test_integration/test_legacy_clients.py
-            controller_suffix: '-trusts'
-            config_template: |
-                domains:
-                  - hosts:
-                      - name: master.ipa.test
-                        role: trust_master
-                      - name: legacy_client_sssd_redhat.ipa.test
-                        role: legacy_client_sssd_redhat
-                      - name: legacy_client_nss_ldap_redhat.ipa.test
-                        role: legacy_client_nss_ldap_redhat
-                      - name: legacy_client_nss_pam_ldapd_redhat.ipa.test
-                        role: legacy_client_nss_pam_ldapd_redhat
-                    name: ipa.test
-                    type: TRUST_IPA
-                  - hosts:
-                      - name: ad.ad.test
-                        role: ad
-                      - name: child.child.ad.test
-                        role: ad_subdomain
-                    name: ad.test
-                    type: AD
+#        - '{prefix}-integration-{project}-{pretty_name}':
+#            pretty_name: basic_trust
+#            suite: test_integration/test_trust.py
+#            controller_suffix: '-trusts'
+#            config_template: |
+#                domains:
+#                  - hosts:
+#                      - name: master.ipa.test
+#                        role: trust_master
+#                    name: ipa.test
+#                    type: TRUST_IPA
+#                  - hosts:
+#                      - name: ad.ad.test
+#                        role: ad
+#                      - name: child.child.ad.test
+#                        role: ad_subdomain
+#                    name: ad.test
+#                    type: AD
 
 - job-group:
     name: ipa-4-1-additions
@@ -640,21 +587,21 @@
             charset: UTF-8
 
 ######### Meta-tests; use these for experimenting
-
-- job-template:
-    name: test1
-    node: master
-    builders:
-        shell: "echo 1"
-
-- job-template:
-    name: test2
-    node: master
-    builders:
-        shell: "echo 1"
-
-- project:
-    name: test
-    jobs:
-        - test1
-        - test2
+#
+# - job-template:
+#     name: test1
+#     node: master
+#     builders:
+#         shell: "echo 1"
+#
+# - job-template:
+#     name: test2
+#     node: master
+#     builders:
+#         shell: "echo 1"
+#
+# - project:
+#     name: test
+#     jobs:
+#         - test1
+#         - test2
